// Generates projects/<slug>/index.html for every entry in src/content/projects.json.
// Run with `npm run projects` after adding or editing a project.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const projects = JSON.parse(readFileSync('src/content/projects.json', 'utf8')).projects.filter((p) => !p.hidden);
const manifest = JSON.parse(readFileSync('src/media-manifest.json', 'utf8'));
const AP = '<span class="ap" aria-hidden="true"><svg><use href="#i-arrow"/></svg><svg><use href="#i-arrow"/></svg></span>';
const pad = (n) => String(n).padStart(2, '0');
const esc = (s = '') => s.replace(/&(?!\w+;|#\d+;)/g, '&amp;').replace(/"/g, '&quot;');
const needs = (label) => `<span class="needs">[NEEDS COPY: ${label}]</span>`;

function hero(p) {
  if (p.heroVideo) {
    return `<figure class="phero__media" data-ph-media>
          <video muted loop playsinline preload="metadata" poster="${p.heroVideo.poster}" data-hero-video aria-hidden="true"><source src="${p.heroVideo.src}" type="video/mp4"></video>
        </figure>`;
  }
  // Photographs too small to fill the screen are framed rather than stretched.
  if ((manifest[p.cover]?.width || 0) < 1600) {
    return `<figure class="phero__media phero__media--framed" data-ph-media>
          <img data-pic="${p.cover}" sizes="(min-width: 1100px) 1000px, 100vw" loading="eager" fetchpriority="high" alt="${esc(p.coverAlt)}">
        </figure>`;
  }
  return `<figure class="phero__media" data-ph-media>
          <img data-pic="${p.cover}" sizes="calc(100vw - 32px)" loading="eager" fetchpriority="high" alt="${esc(p.coverAlt)}">
        </figure>`;
}

function gallery(p) {
  if (!p.gallery?.length) return '';
  const blocks = p.gallery.map((g) => {
    if (g.type === 'pair' && g.pics.length >= 2) {
      const [a, b] = g.pics;
      return `        <div class="side">
          <figure class="side__a" data-reveal><img data-pic="${a.pic}" sizes="(min-width: 861px) 40vw, 100vw" alt="${esc(a.alt)}"></figure>
          <figure class="side__b" data-reveal><img data-pic="${b.pic}" sizes="(min-width: 861px) 58vw, 100vw" alt="${esc(b.alt)}"></figure>
        </div>`;
    }
    const [a] = g.pics;
    return `        <div class="shot shot--wide"><figure class="shot__img" data-reveal><img data-pic="${a.pic}" sizes="100vw" alt="${esc(a.alt)}"></figure></div>`;
  }).join('\n');
  const note = p.galleryNote ? `\n        <p class="wrap shot__cap">${p.galleryNote}</p>` : '';
  return `      <section data-theme="light" aria-label="Photographs">
${blocks}${note}
      </section>`;
}

function related(p) {
  if (!p.related) return '';
  return `      <section data-theme="light" aria-label="Related expertise">
        <div class="wrap grid ptext">
          <h2 class="t-l ptext__title" data-lines>${p.related.title}</h2>
          <div class="ptext__body">
            <p class="needs">[NEEDS COPY: what was designed and installed here, and how it is used]</p>
            <a class="link-arrow" href="${p.related.href}"><span class="link-arrow__t">${p.related.label}</span>${AP}</a>
          </div>
        </div>
      </section>`;
}

projects.forEach((p, i) => {
  const next = projects[(i + 1) % projects.length];
  const meta = [p.location, p.kind].filter(Boolean).join(' · ');
  const html = `<!doctype html>
<html lang="en-IN">
<head>
<!-- @include head -->
  <title>${p.name} — Edomotics</title>
  <meta name="description" content="${esc(p.name)}, a ${p.kind.toLowerCase()} by Edomotics. ${esc(p.lead.replace(/<[^>]+>/g, ''))}">
  <meta property="og:title" content="${esc(p.name)} — Edomotics">
  <meta property="og:description" content="${esc(p.name)}, a ${p.kind.toLowerCase()} by Edomotics.">
  <meta property="og:image" content="/media/img/${p.cover}-md.webp">
</head>
<body>
<!-- @include chrome -->

  <!-- Generated by scripts/projects.mjs from src/content/projects.json — edit the data, not this file. -->
  <div class="view" data-view data-page="project">
    <main id="main">

      <section class="phero phero--center" data-theme="light" data-page-hero aria-labelledby="page-title">
        <div class="wrap grid phero__head">
          <div class="phero__title-wrap">
            <p class="phero__label" data-ph-label>${pad(i + 1)} / ${pad(projects.length)} · ${meta}</p>
            <h1 class="t-name" id="page-title" data-ph-title>${p.title}</h1>
          </div>
          <div class="phero__aside" data-ph-aside>
            <p class="needs">[NEEDS COPY: a one-line summary of the project]</p>
          </div>
        </div>
        ${hero(p)}
      </section>

      <section data-theme="light" aria-label="Project details">
        <div class="wrap grid pinfo">
          <p class="t-lead pinfo__lead">${p.lead}</p>
          <dl class="pinfo__meta">
            <div><dt>Type</dt><dd>${p.kind}</dd></div>
            <div><dt>Location</dt><dd>${p.location || needs('city')}</dd></div>
            <div><dt>Systems</dt><dd>${p.systems || needs('what was installed')}</dd></div>
            <div><dt>Year</dt><dd>${p.year || needs('completion year')}</dd></div>
            <div><dt>Architect &amp; interiors</dt><dd>${p.credits || needs('credits')}</dd></div>
            <div><dt>Photography</dt><dd>${p.photographer || needs('photographer credit')}</dd></div>
          </dl>
        </div>
      </section>

${gallery(p)}
${related(p)}

      <section data-theme="light" aria-label="${p.gallery?.length ? 'All projects' : 'Still to come'}">${p.gallery?.length ? '' : `
        <div class="gap-note">
          <strong>More of this home to follow.</strong>
          <p>[NEEDS COPY: further photographs, and the story of the project — the brief, the rooms, the systems and how the family uses them]</p>
        </div>`}
        <div class="wrap" style="padding-block: ${p.gallery?.length ? 'var(--block)' : '24px var(--block)'};">
          <a class="link-arrow" href="/projects/"><span class="link-arrow__t">All projects</span>${AP}</a>
        </div>
      </section>

      <section data-theme="dark" aria-label="Next project">
        <a class="pnext" href="/projects/${next.slug}/">
          <div class="pnext__img"><img data-pic="${next.cover}" sizes="100vw" alt=""></div>
          <div class="pnext__in wrap">
            <p class="pnext__label">Next project</p>
            <p class="t-xl">${next.name}</p>
            <span class="link-arrow"><span class="link-arrow__t">View project</span>${AP}</span>
          </div>
        </a>
      </section>
    </main>
<!-- @include footer -->
  </div>
</body>
</html>
`;
  mkdirSync(`projects/${p.slug}`, { recursive: true });
  writeFileSync(`projects/${p.slug}/index.html`, html);
  console.log('page', `/projects/${p.slug}/`);
});
